version: "3.5"

services:
  mongo:
    image: mongo:6.0
    container_name: mongo_profile
    environment:
      MONGO_INITDB_ROOT_USERNAME: $USER_PROFILE_MONGO_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $USER_PROFILE_MONGO_PASSWORD
    ports:
      - "0.0.0.0:$USER_PROFILE_MONGO_PORT:27017"
    networks:
      - EOSC_USER_PROFILE_MONGO
    volumes:
      - type: volume
        source: EOSC_USER_PROFILE_MONGO_DATA
        target: /data/db
      - type: volume
        source: EOSC_USER_PROFILE_MONGO_CONFIG
        target: /data/configdb
      - type: bind
        source: ./storage/dumps/recommender
        target: /dump/recommender

  redis:
    image: redis:6.2-alpine
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass $INTERNAL_REDIS_PASSWORD
    volumes:
      - type: volume
        source: EOSCF_USER_PROFILE_REDIS_DATA
        target: /data

networks:
  EOSC_USER_PROFILE_MONGO:
    name: EOSC_USER_PROFILE_MONGO
  EOSC_USER_PROFILE_POSTGRES:
    name: EOSC_USER_PROFILE_POSTGRES
    driver: bridge

volumes:
  EOSC_USER_PROFILE_MONGO_DATA:
    name: EOSC_USER_PROFILE_MONGO_DATA
  EOSC_USER_PROFILE_MONGO_CONFIG:
    name: EOSC_USER_PROFILE_MONGO_CONFIG
  EOSCF_USER_PROFILE_POSTGRES_DATA:
    name: EOSCF_USER_PROFILE_POSTGRES_DATA
  EOSCF_USER_PROFILE_REDIS_DATA:
    name: EOSCF_USER_PROFILE_REDIS_DATA
